### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character 

### ISSUE THREAD

**Issue by 53to29** [microelly2/freecad-objecttree#1]
Good afternoon,
I please your macro and play with it in order to build bill of material on an spreadheet.
I have some error with ascii as i'm french with as you know some special character.
For example , in french freecad install on windows, if i add a sphere the object name is "sphère".
The object tree macro give this error 
  File "<string>", line 210, in initBuff
-->    File "<string>", line 59, in say
-->  UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 3: ordinal not in range(128)

I investigate without success how to solve it. 
Could you help me.

**Comment by microelly2** [comment]
Change your encoding

import sys
reload(sys)
sys.setdefaultencoding('utf-8')
 say(App.ActiveDocument.ActiveObject.Label)

**Comment by 53to29** [comment]
Thanks a lot for your support.
I change my coding according to your suggestion.
I also change all my "print" instruction to say() instruction
It's works know

2016-09-10 11:45 GMT+02:00 microelly2 notifications@github.com:
